"""added superhero table

Revision ID: 10806823d5ab
Revises: 
Create Date: 2023-05-16 11:01:23.277105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10806823d5ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('attribute', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('super_heroes')
    # ### end Alembic commands ###
